# This is a basic workflow to help you get started with Actions

name: Upload release

on:
  push:
    tags:
      - 'v*'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  contents: write
  checks: write

  actions: read
  issues: read
  packages: write
  pull-requests: read
  repository-projects: read
  statuses: read

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@v3

      - name: Create archive
        run: tar -czvf nahui.tar.gz --exclude='readme.md' *   # Створення архіву

      - name: Upload artifacts
        uses: actions/upload-artifact@v2   # Використання вбудованої дії для завантаження артефактів
        with:
          name: nahui-artifact
          path: nahui.tar.gz   # Шлях до архіву, який потрібно завантажити

      - name: Upload files
      - uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          artifacts: "nahui.tar.gz"
